#pragma once

#include "core/application.h"
#include "core/log.h"
#include "core/platform.h"
#include "core/event.h"
#include "core/layer.h"
#include "core/time.h"
#include "core/window.h"
#include "core/layer_stack.h"
#include "core/input.h"
#include "core/mouse_buttons.h"
#include "core/joystick_buttons.h"
#include "core/keys.h"

#include "utils/debug_timer.h"
#include "utils/fixed_update.h"
#include "utils/delta.h"
#include "utils/file_utils.h"
#include "utils/math.h"
#include "utils/RNG.h"
#include "utils/timers.h"
#include "utils/detected.h"

#include "gfx/graphics.h"
#include "gfx/enums.h"
#include "gfx/shader.h"
#include "gfx/command_pool.h"
#include "gfx/descriptor_pool.h"
#include "gfx/descriptor_set.h"
#include "gfx/descriptor_set_layout.h"
#include "gfx/graphics_pipeline.h"
#include "gfx/image.h"
#include "gfx/image_view.h"
#include "gfx/render_pass.h"
#include "gfx/sampler.h"
#include "gfx/query_pool.h"
#include "gfx/vertex_array.h"

#include "gfx/buffers/buffer.h"
#include "gfx/buffers/vertex_buffer.h"
#include "gfx/buffers/index_buffer.h"
#include "gfx/buffers/command_buffer.h"
#include "gfx/buffers/framebuffer.h"
#include "gfx/buffers/staging_buffer.h"
#include "gfx/buffers/buffer_layout.h"
#include "gfx/buffers/uniform_buffer.h"

#include "scene/vertex.h"
#include "scene/entity.h"
#include "scene/scene.h"
#include "scene/components.h"
#include "scene/camera_controller.h"
