# Vulkan
find_package(Vulkan REQUIRED COMPONENTS shaderc_combined)
list(APPEND EXTRA_LIBS ${Vulkan_LIBRARIES} Vulkan::shaderc_combined)

include(BuildExternalProject)

# External Projects
externalProject(NAME freetype INCLUDE_DIR freetype2)
externalProject(NAME glfw BUILD_ARGS
    -DGLFW_BUILD_EXAMPLES=OFF
    -DGLFW_BUILD_DOCS=OFF
    -DGLFW_BUILD_TESTS=OFF
)
externalProject(NAME assimp BUILD_ARGS 
    -DASSIMP_BUILD_ALL_IMPORTERS_BY_DEFAULT=OFF
    -DASSIMP_BUILD_ALL_EXPORTERS_BY_DEFAULT=OFF
    -DASSIMP_BUILD_ASSIMP_TOOLS=OFF
    -DASSIMP_BUILD_TESTS=OFF
    -DASSIMP_NO_EXPORT=ON
    -DASSIMP_BUILD_FBX_IMPORTER=ON
    -DASSIMP_BUILD_OBJ_IMPORTER=ON
    -DASSIMP_BUILD_glTF_IMPORTER=ON
    -DASSIMP_BUILD_glTF2_IMPORTER=ON
    -DASSIMP_BUILD_ZLIB=ON
    -DBUILD_SHARED_LIBS=OFF
)
externalProject(NAME openal BUILD_ARGS
    -DALSOFT_INSTALL_EXAMPLES=OFF
    -DALSOFT_INSTALL_AMBDEC_PRESETS=OFF
    -DALSOFT_INSTALL_CONFIG=OFF
    -DALSOFT_INSTALL_UTILS=OFF
    -DALSOFT_INSTALL_HRTF_DATA=OFF
    -DALSOFT_EXAMPLES=OFF
    -DALSOFT_UTILS=OFF
    -DALSOFT_NO_CONFIG_UTIL=ON
    -DLIBTYPE=STATIC
)
externalProject(NAME spirv_cross BUILD_ARGS 
    -DSPIRV_CROSS_CLI=OFF
    -DSPIRV_CROSS_ENABLE_GLSL=OFF
    -DSPIRV_CROSS_ENABLE_HLSL=OFF
    -DSPIRV_CROSS_ENABLE_TESTS=OFF
    -DSPIRV_CROSS_ENABLE_MSL=OFF
    -DSPIRV_CROSS_ENABLE_CPP=OFF
    -DSPIRV_CROSS_ENABLE_REFLECT=OFF
    -DSPIRV_CROSS_ENABLE_UTIL=OFF
)