#pragma once

#include <iostream>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <map>
#include <set>
#include <vector>
#include <chrono>
#include <sstream>
#include <fstream>
#include <memory>
#include <functional>
#include <algorithm>
#include <utility>
#include <array>
#include <random>
#include <stdlib.h>
#include <thread>
#include <queue>
#include <mutex>
#include <condition_variable>
#include <bit>
#include <math.h>
#include <filesystem>
#include <future>
#include <stdexcept>
#include <cstdlib>
#include <numeric>
#include <optional>
#include <typeindex>
#include <typeinfo>
#include <list>

#include <GLM/glm.hpp>
#include <GLM/gtc/matrix_transform.hpp>
#include <GLM/gtx/quaternion.hpp>
//#include <assimp/Importer.hpp>
//#include <assimp/scene.h>
//#include <assimp/postprocess.h>
#include <vulkan/vulkan.h>
#include <GLFW/glfw3.h>
//#include <ft2build.h>
//#include <freetype/freetype.h>
//#include <AL/al.h>
//#include <AL/alc.h>
//#include <AL/efx.h>

#include "base.h"
#include "log.h"